version: '3'
# 
services:
  flask_api:
    image: flask_hw_test:3
    ports:
      - 8585:8585
    volumes:
      - ./src:/app
    command: gunicorn --bind 0.0.0.0:80 --workers 2 main:app
    #command: python main.py

#When you use compose or swarm to deploy multiple services, use service name in tunnel creation to
# to refer to your webservice. e.g = if you use this file use flask_api:80 in webhook relay
  webhookrelay:
    container_name: drone-webhookrelay
    image: webhookrelay/webhookrelayd:latest
    command:
      - --mode 
      - tunnel 
      - -t
      - <name_tunnel>
    restart: always
    environment: 
      - KEY=<WEBHOOK_KEY_VAL>
      - SECRET=<WEBHOOK_SECRET_VAL>


 